spring.application.name=room-service

# Database Connection — values come from environment variables
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/room_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

# Hibernate/JPA Settings (This creates the tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Set port to 8081 so it doesn't clash with other services later
server.port=8081