# Database Connection (Pointing to the new guest_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/guest_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Set port to 8082 so it doesn't clash with room-service
server.port=8082