# --- SERVER CONFIGURATION ---
server.port=8084
spring.application.name=hotel-service

# --- DATABASE CONFIGURATION (PostgreSQL) ---
# It will connect to a new database named 'hotel_db'
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
# Replace 'YOUR_PASSWORD_HERE' with your actual pgAdmin password!
spring.datasource.password=123456

# --- HIBERNATE / JPA CONFIGURATION ---
# This tells Spring to automatically create your tables!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true