# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Set port to 8083
server.port=8083